### ISSUE TITLE
Missing p2p component

### ISSUE THREAD

**Issue by serkandyck** [gpfduoduo/AnyShareOfAndroid#1]
import com.guo.duoduo.anyshareofandroid.sdk.p2p.p2pentity.P2PNeighbor;
import com.guo.duoduo.anyshareofandroid.sdk.p2p.p2pinterface.Melon_Callback;
import com.guo.duoduo.anyshareofandroid.sdk.p2p.p2pinterface.SendFile_Callback;
import com.guo.duoduo.anyshareofandroid.sdk.p2p.p2pconstant.P2PConstant;
import com.guo.duoduo.anyshareofandroid.sdk.p2p.p2pcore.P2PManager;

**Comment by gpfduoduo** [comment]
readme写了 暂时还没有上传。在修改 不好意思稍等片刻

**Comment by serkandyck** [comment]
ahh, sorry i missed

**Comment by Lakkichand** [comment]
Please add missing files

**Comment by gpfduoduo** [comment]
missed files have been uploaded @asdstyle33 @Lakkichand
