### ISSUE TITLE
项目文件缺失

### ISSUE THREAD

**Issue by 645947429** [gpfduoduo/AnyShareOfAndroid#3]
包com.guo.duoduo.anyshareofandroid.sdk.p2p 缺失文件

**Comment by gpfduoduo** [comment]
P2P相关拿出来组成module了……应该没有缺失……

**Comment by 645947429** [comment]
谢谢大神, 已经解决了

在 2016-06-18 16:25:37，"郭攀峰" notifications@github.com 写道：

P2P相关拿出来组成module了……应该没有缺失……
